name: innereye
channels:
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - pip
  - ipython
  - jupyter
  - numpy
  - scipy
  - matplotlib
  - openjdk
  - pip:
      - fire
      - h5py
      - scikit-image
      - scikit-learn
      - pathos
      - bioformats
      - numba
      - networkx
      - editdistance
